language: python
python:
  - "2.7"
  - "3.6"

install: "python install.py"

script:
  - nosetests --verbose --rednose --with-coverage --cover-erase --cover-package=derivatex

after_success:
  - coveralls

notifications:
  email: false